# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAccessBarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('barrier_symbol', models.CharField(blank=True, max_length=50, verbose_name='WTO Symbol')),
                ('notifying_member', models.CharField(blank=True, max_length=100, verbose_name='Notifying Member(s)')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('distribution_date', models.DateField(blank=True, verbose_name='Distribution Date')),
                ('products_text', models.CharField(blank=True, max_length=300, verbose_name='Products')),
                ('product_codes', models.CharField(blank=True, max_length=300, verbose_name='Product codes')),
                ('objectives', models.CharField(blank=True, max_length=300, verbose_name='Objectives')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='Keywords')),
                ('regions_affected', models.CharField(blank=True, max_length=300, verbose_name='Regions affected')),
                ('comments_due_date', models.DateField(blank=True, verbose_name='Final date for comments')),
                ('notification_type', models.CharField(blank=True, max_length=50, verbose_name='Notification type')),
                ('document_link', models.CharField(blank=True, max_length=500, verbose_name='Document link')),
                ('wto_link', models.CharField(blank=True, max_length=500, verbose_name='WTO ePing link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
