# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0002_auto_20170821_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='title',
            field=models.CharField(blank=True, max_length=800, verbose_name='Title'),
        ),
    ]
