# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0003_auto_20170823_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='document_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Document link'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='keywords',
            field=models.CharField(blank=True, max_length=800, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='objectives',
            field=models.CharField(blank=True, max_length=800, verbose_name='Objectives'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='product_codes',
            field=models.CharField(blank=True, max_length=800, verbose_name='Product codes'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='products_text',
            field=models.CharField(blank=True, max_length=800, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='regions_affected',
            field=models.CharField(blank=True, max_length=800, verbose_name='Regions affected'),
        ),
    ]
