# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0005_auto_20170823_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='barrier_symbol',
            field=models.CharField(blank=True, max_length=500, verbose_name='WTO Symbol'),
        ),
    ]
