# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0006_auto_20170823_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='Objectives'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='product_codes',
            field=models.TextField(blank=True, verbose_name='Product codes'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='products_text',
            field=models.TextField(blank=True, verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='regions_affected',
            field=models.TextField(blank=True, verbose_name='Regions affected'),
        ),
        migrations.AlterField(
            model_name='marketaccessbarrier',
            name='title',
            field=models.TextField(blank=True, verbose_name='Title'),
        ),
    ]
