# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0007_auto_20170823_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketaccessbarrier',
            old_name='barrier_symbol',
            new_name='wto_symbol',
        ),
        migrations.AddField(
            model_name='marketaccessbarrier',
            name='core_symbol',
            field=models.CharField(blank=True, max_length=500, verbose_name='WTO Symbol'),
        ),
        migrations.AddField(
            model_name='marketaccessbarrier',
            name='mab_type',
            field=models.CharField(blank=True, max_length=500, verbose_name='WTO Symbol'),
        ),
    ]
