# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:58
from __future__ import unicode_literals

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0010_auto_20170904_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barriertypes',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='barriertypes',
            name='barrier_type',
        ),
        migrations.AddField(
            model_name='marketaccessbarrier',
            name='barrier_types',
            field=mptt.fields.TreeManyToManyField(blank=True, db_index=True, related_name='barrier_types', to='barriers.BarrierType'),
        ),
        migrations.DeleteModel(
            name='BarrierTypes',
        ),
    ]
