# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0014_auto_20171004_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barriercountry',
            name='country_or_territory',
            field=models.CharField(choices=[('country', 'Country'), ('territory', 'Territory'), ('bloc', 'Trade Bloc')], default='country', max_length=10, verbose_name='Country or Territory flag'),
        ),
    ]
