# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0016_barriernotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierrecord',
            name='actions_taken',
            field=models.TextField(blank=True, null=True, verbose_name='Actions taken'),
        ),
        migrations.AddField(
            model_name='barrierrecord',
            name='companies_affected',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Companies affected'),
        ),
        migrations.AddField(
            model_name='barrierrecord',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='barrierrecord',
            name='uk_reference_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='UK reference code'),
        ),
        migrations.AlterField(
            model_name='barrierrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Assessment', 'Assessment')], default=None, max_length=10, null=True),
        ),
    ]
